config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => [:registrations], controllers: { 
    sessions: 'admins/sessions',
  }
  authenticate :admin do 
    mount Resque::Server.new, :at => "/dashboard/jobs"
  end  
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'    
    patch 'admins' => 'devise/registrations#update', :as => 'admin_registration'            
  end

  devise_for :students, :skip => [:registrations], controllers: { 
    sessions: 'students/sessions',
  }
  as :student do
    get 'students/edit' => 'devise/registrations#edit', :as => 'edit_student_registration'    
    patch 'students' => 'devise/registrations#update', :as => 'student_registration'            
  end

  devise_for :employers, controllers: { 
    sessions: 'employers/sessions',
    registrations: 'employers/registrations'
  }

  root 'pages#setup_root'
  
  get '/sign_in' => 'pages#sign_in', as: :home_sign_in
  get '/students/invitations/batch' => 'students#batch', as: :student_batch_invite
  get '/employers/invitations/batch' => 'employers#batch', as: :employer_batch_invite
  get '/admins/invitations/batch' => 'admins#batch', as: :admin_batch_invite

  namespace :api do
    namespace :v1 do
      resources :admins
      resources :students
      resources :employers
      resources :employer_email_records
    end
  end

  resources :admins
    get '/dashboard' => 'admins#admin_center', as: :admin_center
    get '/admin/admins/new' => 'admins#new', as: :new_admin_admin
    post '/admin/admins/new' => 'admins#create', as: :admin_admins
    get '/admin/students/new' => 'students#new', as: :new_admin_student
    post '/admin/students' => 'students#create', as: :admin_students
    get '/admin/employers/new' => 'employers#new', as: :new_admin_employer
    post '/admin/employers' => 'employers#create', as: :admin_employers
  
  resources :students
  resources :employers
  resources :projects
  resources :technologies
  resources :salary_ranges
  resources :industries
  resources :position_types
  resources :positions
  resources :cohort_cities
  resources :follow_up_students
  resources :batch_invitations

  post '/employer_emails' => 'employer_emails#create'
  post '/student_emails' => 'student_emails#create'

end

app/views/admins/edit.html.erb
<div class="login-page">
  <section id="content-region-3" class="padding-40 page-tree-bg">
    <div class="container">
      <h3 class="page-tree-text">Update Admin Account</h3>
    </div>
  </section><!--page-tree end here-->

  <div class="space-70"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="my-login-form">
          <%= form_for(@admin, url: admin_path(@admin), html: { :multipart => true }) do |f| %>
          <%= f.hidden_field :active, value: true %>
            <% if @admin.errors.any? %>
              <div class="alert alert-dismissible alert-warning center-warning">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h3>You forgot to fill out
                  <%= pluralize(@admin.errors.count, "field") %>:
                </h3>
                <ul>
                  <% @admin.errors.full_messages.each do |msg| %>
                    <h5><%= msg %></h5>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <h4 class="heading-mini">Update Account Details</h4><hr>
            <div class="row">
              <div class="form-group col-md-6">
                <%= f.label :first_name %><span class="required-form-field"> *</span><br />
                <%= f.text_field :first_name, class: "form-control" %>
              </div>
              <div class="form-group col-md-6">
                <%= f.label :last_name %><span class="required-form-field"> *</span><br />
                <%= f.text_field :last_name, class: "form-control" %>
              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-12">
                <%= f.label :email %><span class="required-form-field"> *</span><br />
                <%= f.email_field :email, class: "form-control" %>
              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-12">
                <%= f.label :password %><br />
                <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-12">
                <%= f.label :password_confirmation %><br />
                <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
              </div>
            </div>
            <% if @admin.avatar.url && @admin.avatar.url.include?("aws") %>
              <div class="row">
                <div class="form-group col-md-12">
                  <%= f.label "Current Avatar" %><br />
                  <%= image_tag @admin.avatar.thumb.url, class: "form-img-preview" %>
                </div>
              </div>
              <div class="row">
                <div class="form-group col-md-12">
                  <%= f.label :avatar, "Change Avatar" %><br />
                  <%= f.file_field :avatar, class: "form-control", id: "control" %>
                </div>
              </div><br>
            <% else %>
              <div class="row">
                <div class="form-group col-md-12">
                  <%= f.label :avatar, "Upload Avatar" %><br />
                  <%= f.file_field :avatar, class: "form-control", id: "control" %>
                </div>
              </div><br>
            <% end %>
            <div class="row">
              <div class="text-right submit-btn col-md-12">
                <%= f.submit "Update", class: "btn theme-btn-color" %>
              </div>
            </div>
          <% end -%>
        </div>
      </div>
    </div>
  </div><!--login page container end-->
</div>

<%= render "shared/alerts_checkbox_radio_scripts" %>

app/views/admins/index.html.erb
<div class="container-fluid" id="admin-index">
  <div class="row">
    <ul>
    <% @admins.each do |admin| %>
      <div class="indiv-admin">
        <li>
          <%= image_tag(admin.avatar.thumb.url) %>
          <h3><%= link_to admin.full_name, admin_path(admin) %></h3>
          <p><%= admin.email %></p>
          <br>
          <%= link_to 'Edit Profile', edit_admin_path(admin), class: "btn btn-default btn-xs" %>
          <%= link_to 'Delete', admin_path(admin), method: :delete, data: { confirm: "Are you sure you want to delete '#{admin.full_name}'"}, class: "btn btn-default btn-xs" %>
        </li>
      </div>
    <% end %>
    </ul>
  </div> 
</div>

app/views/admins/new.html.erb
<div class="login-page">
  <section id="content-region-3" class="padding-40 page-tree-bg">
    <div class="container">
      <h3 class="page-tree-text">Admin Sign Up</h3>
    </div>
  </section><!--page-tree end here-->

  <div class="space-70"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="my-login-form">
          <%= form_for(@admin, url: admin_admins_path, html: { :multipart => true }) do |f| %>
          <%= f.hidden_field :active, value: true %>
            <% if @admin.errors.any? %>
              <div class="alert alert-dismissible alert-warning center-warning">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h3>You forgot to fill out
                  <%= pluralize(@admin.errors.count, "field") %>:
                </h3>
                <ul>
                  <% @admin.errors.full_messages.each do |msg| %>
                    <h5><%= msg %></h5>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <h4 class="heading-mini">Account Details</h4><hr>
            <div class="row">
              <div class="form-group col-md-6">
                <%= f.label :first_name %><span class="required-form-field"> *</span><br />
                <%= f.text_field :first_name, class: "form-control" %>
              </div>
              <div class="form-group col-md-6">
                <%= f.label :last_name %><span class="required-form-field"> *</span><br />
                <%= f.text_field :last_name, class: "form-control" %>
              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-12">
                <%= f.label :email %><span class="required-form-field"> *</span><br />
                <%= f.email_field :email, class: "form-control" %>
              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-12">
                <%= f.label :password %><span class="required-form-field"> *</span><br />
                <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-12">
                <%= f.label :password_confirmation %><span class="required-form-field"> *</span><br />
                <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
              </div>
            </div>
            <div class="row">
              <div class="text-right submit-btn col-md-12">
                <%= f.submit "Sign Up", class: "btn theme-btn-color" %>
              </div>
            </div>
            <hr class="login-break">
            <div class="shared-links">
              <div class="form-btm-link text-center devise-links">
              <%= link_to "Already have an account? Log in!", new_admin_session_path %>
              </div>  
            </div>
          <% end -%>
        </div>
      </div>
    </div>
  </div><!--login page container end-->
</div>

<%= render "shared/alerts_checkbox_radio_scripts" %>