config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => [:registrations], controllers: { 
    sessions: 'admins/sessions',
  }
  authenticate :admin do 
    mount Resque::Server.new, :at => "/dashboard/jobs"
  end  
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'    
    patch 'admins' => 'devise/registrations#update', :as => 'admin_registration'            
  end

  devise_for :students, :skip => [:registrations], controllers: { 
    sessions: 'students/sessions',
  }
  as :student do
    get 'students/edit' => 'devise/registrations#edit', :as => 'edit_student_registration'    
    patch 'students' => 'devise/registrations#update', :as => 'student_registration'            
  end

  devise_for :employers, controllers: { 
    sessions: 'employers/sessions',
    registrations: 'employers/registrations'
  }

  root 'pages#setup_root'
  
  get '/sign_in' => 'pages#sign_in', as: :home_sign_in
  get '/students/invitations/batch' => 'students#batch', as: :student_batch_invite
  get '/employers/invitations/batch' => 'employers#batch', as: :employer_batch_invite
  get '/admins/invitations/batch' => 'admins#batch', as: :admin_batch_invite

  namespace :api do
    namespace :v1 do
      resources :admins
      resources :students
      resources :employers
      resources :employer_email_records
    end
  end

  resources :admins
    get '/dashboard' => 'admins#admin_center', as: :admin_center
    get '/admin/admins/new' => 'admins#new', as: :new_admin_admin
    post '/admin/admins/new' => 'admins#create', as: :admin_admins
    get '/admin/students/new' => 'students#new', as: :new_admin_student
    post '/admin/students' => 'students#create', as: :admin_students
    get '/admin/employers/new' => 'employers#new', as: :new_admin_employer
    post '/admin/employers' => 'employers#create', as: :admin_employers
  
  resources :students
  resources :employers
  resources :projects
  resources :technologies
  resources :salary_ranges
  resources :industries
  resources :position_types
  resources :positions
  resources :cohort_cities
  resources :follow_up_students
  resources :batch_invitations

  post '/employer_emails' => 'employer_emails#create'
  post '/student_emails' => 'student_emails#create'

end

app/controllers/position_types_controller.rb
class PositionTypesController < ApplicationController
  before_action :set_position_type, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:index]
  
  # GET /position_types
  # GET /position_types.json
  def index
    @position_types = PositionType.all
    @position_type = PositionType.new
  end

  # GET /position_types/1
  # GET /position_types/1.json
  def show
  end

  # GET /position_types/new
  def new
    @position_type = PositionType.new
  end

  # GET /position_types/1/edit
  def edit
  end

  # POST /position_types
  # POST /position_types.json
  def create
    @position_type = PositionType.new(position_type_params)

    respond_to do |format|
      if @position_type.save
        flash[:success] = 'The new position type was successfully created.'
        format.html { redirect_to position_types_path }
        format.json { render :show, status: :created, location: @position_type }
      else
        flash[:warning] = 'Unable to add new position type.'
        format.html { render :index }
        format.json { render json: @position_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /position_type/1
  # PATCH/PUT /position_type/1.json
  def update
    respond_to do |format|
      if @position_type.update(position_type_params)
        flash[:success] = 'The position type was successfully updated.'
        format.html { redirect_to position_types_path }
        format.json { render :show, status: :ok, location: @position_type }
      else
        flash[:warning] = 'Unable to update position type.'
        format.html { render :edit }
        format.json { render json: @position_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /position_type/1
  # DELETE /position_type/1.json
  def destroy
    @position_type.destroy
    respond_to do |format|
      flash[:success] = 'Position type successfully deleted.'
      format.html { redirect_to position_types_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position_type
      @position_type = PositionType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_type_params
      params.require(:position_type).permit(:name)
    end
end

app/helpers/position_types_helper.rb
module PositionTypesHelper
end

app/views/position_types/_form.html.erb
<%= form_for(@position_type) do |f| %> 
  <div class="col-md-4 margin-btm-20">
    <div>
      <%= f.text_field :name, class: "form-control", placeholder: "Position type name" %>
    </div><br>
    <div>
      <%= f.submit "Submit", class: "btn theme-btn-color" %>
    </div>
  </div>
<% end %>

app/views/position_types/edit.html.erb
<div id="position-type-index">
  <section id="content-region-3" class="padding-40 page-tree-bg">
    <div class="container">
      <h3 class="page-tree-text">
          Edit <em><%= @position_type.name %></em>
      </h3>
    </div>
  </section><!--page-tree end here-->
  <div class="space-70"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h4 class="heading-mini">Update Position Type Name</h4>
      </div>
      <div>
        <%= render 'form' %>
      </div>
    </div>
  </div><!--right sidebar page end-->
</div>

app/views/position_types/index.html.erb
<div id="position-type-index">
  <div ng-app="app">
    <div ng-controller="positionTypesCtrl" ng-init="setupPositionTypeIndex()">

      <section id="content-region-3" class="padding-40 page-tree-bg">
        <div class="container">
          <h3 class="page-tree-text">
              Manage Position Types
          </h3>
        </div>
      </section><!--page-tree end here-->
      <div class="space-70"></div>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h4 class="heading-mini">Add A Position Type</h4>
          </div>
          <div>
            <%= render 'form' %>
          </div>
        </div>
        <div class="row">
 
          <div class="col-md-12">
            <h4 class="heading-mini">Current Position Types</h4>
            <div class="admin-center-search">
              <div class="form-group">
                <input type="text" ng-model="searchPositionTypeName" class="form-control admin-center-search-bar" placeholder="Search current position types">
              </div>
            </div>
            <table class="table table-hover table-responsive">
              <tbody>
                <tr class="hover-list" ng-repeat="position_type in positionTypes | filter: { name: searchPositionTypeName } | orderBy: 'name'">
                  <td class="user-entries is-breakable"><p>{{ position_type.name }}</p></td>
                  <td><a href="/position_types/{{ position_type.id }}/edit" class="btn btn-xs btn-default"><i class="ion-edit"></i></a></td>
                  <td><a href="/position_types/{{ position_type.id }}" class="btn btn-xs btn-default" data-method="delete" data-confirm="Are you sure you want to delete '{{ position_type.name }}'?"><i class="ion-trash-a"></i></a></td>
                </tr>
              </tbody>
            </table>
          </div> 
        </div>
      </div><!--right sidebar page end-->
    </div>
  </div>
</div>

app/views/position_types/new.html.erb
<h1>New Position Type</h1>

<%= render 'form' %>

<%= link_to 'Back', position_types_path %>

app/views/position_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @position_type.name %>
</p>

<%= link_to 'Edit', edit_position_type_path(@position_type) %> |
<%= link_to 'Back', position_types_path %>