config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => [:registrations], controllers: { 
    sessions: 'admins/sessions',
  }
  authenticate :admin do 
    mount Resque::Server.new, :at => "/dashboard/jobs"
  end  
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'    
    patch 'admins' => 'devise/registrations#update', :as => 'admin_registration'            
  end

  devise_for :students, :skip => [:registrations], controllers: { 
    sessions: 'students/sessions',
  }
  as :student do
    get 'students/edit' => 'devise/registrations#edit', :as => 'edit_student_registration'    
    patch 'students' => 'devise/registrations#update', :as => 'student_registration'            
  end

  devise_for :employers, controllers: { 
    sessions: 'employers/sessions',
    registrations: 'employers/registrations'
  }

  root 'pages#setup_root'
  
  get '/sign_in' => 'pages#sign_in', as: :home_sign_in
  get '/students/invitations/batch' => 'students#batch', as: :student_batch_invite
  get '/employers/invitations/batch' => 'employers#batch', as: :employer_batch_invite
  get '/admins/invitations/batch' => 'admins#batch', as: :admin_batch_invite

  namespace :api do
    namespace :v1 do
      resources :admins
      resources :students
      resources :employers
      resources :employer_email_records
    end
  end

  resources :admins
    get '/dashboard' => 'admins#admin_center', as: :admin_center
    get '/admin/admins/new' => 'admins#new', as: :new_admin_admin
    post '/admin/admins/new' => 'admins#create', as: :admin_admins
    get '/admin/students/new' => 'students#new', as: :new_admin_student
    post '/admin/students' => 'students#create', as: :admin_students
    get '/admin/employers/new' => 'employers#new', as: :new_admin_employer
    post '/admin/employers' => 'employers#create', as: :admin_employers
  
  resources :students
  resources :employers
  resources :projects
  resources :technologies
  resources :salary_ranges
  resources :industries
  resources :position_types
  resources :positions
  resources :cohort_cities
  resources :follow_up_students
  resources :batch_invitations

  post '/employer_emails' => 'employer_emails#create'
  post '/student_emails' => 'student_emails#create'

end

app/models/project.rb
class Project < ActiveRecord::Base
  mount_uploader :project_image, ProjectImageUploader
  
  belongs_to :student
  has_and_belongs_to_many :technologies

  validates :name, :description, :technologies, presence: true

  def normalized_github
    github && PostRank::URI.normalize(github).to_s
  end

  def normalized_website
    website && PostRank::URI.normalize(website).to_s
  end

  def normalized_screencast
    screencast && PostRank::URI.normalize(screencast).to_s
  end

  def project_type
    if capstone
      "Capstone Project"
    elsif client_work
      "Client Work"
    else
      "Personal Project"
    end
  end

  def screencast?
    if screencast != "" && screencast != nil 
      true
    else
      false
    end
  end

  def embed_youtube_screencast
    if normalized_screencast.include?("youtube") && normalized_screencast.include?("watch?v=") && !normalized_screencast.include?("&feature=")
      link = normalized_screencast
      link_for_embed = link.gsub!("watch?v=", "embed/")
    elsif normalized_screencast.include?("&feature=")
      match_index = /&feature=/ =~ normalized_screencast
      link_end_index = match_index - 1
      remove_feature_link = normalized_screencast[0..link_end_index]
      link = remove_feature_link
      link_for_embed = link.gsub!("watch?v=", "embed/")
    elsif normalized_screencast.include?("youtube") && normalized_screencast.include?("/embed/")
      normalized_screencast
    elsif normalized_screencast.include?("youtu.be/")
      split_sections = normalized_screencast.split("/")
      video_id = split_sections.last
      link_for_embed = "https://www.youtube.com/embed/#{video_id}"
    else 
      false
    end
  end

  def project_links?
    project_links = false

    if github == nil || github == ""
      github_entered = false
    else
      github_entered = true
    end

    if website == nil || website == ""
      website_entered = false
     else
      website_entered = true
    end

    if screencast == nil || screencast == ""
      screencast_entered = false
    else
      screencast_entered = true
    end

    if github_entered || website_entered || screencast_entered
      project_links = true
    end

    project_links
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin_student!, only: [:new, :create, :edit, :update, :destroy]

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:success] = "Project successfully created!"
      redirect_to student_path(@project.student)
    else
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
    @technologies = @project.technologies if @project.technologies.any?
  end

  def edit
    @project = Project.find(params[:id])

    unless admin_signed_in? || student_signed_in? && @project.student_id == current_student.id
      redirect_to students_path
      flash[:warning] = "You do not have access to that page!"
    end
  end

  def update
    @project = Project.find(params[:id])

    if admin_signed_in? || student_signed_in? && @project.student_id == current_student.id
      if @project.update(project_params)
        flash[:success] = "Project successfully updated!"
        redirect_to project_path(@project)
      else 
        render :edit
      end
    else 
      redirect_to students_path
      flash[:warning] = "You do not have access to that page!"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.remove_project_image!
    @project.save

    if admin_signed_in? || student_signed_in? && @project.student_id == current_student.id
      if @project.destroy
        flash[:success] = "Project successfully deleted!"
        redirect_to student_path(@project.student)
      else 
        flash[:warning] = "Unable to delete project."
        redirect_to student_path(@project.student)
      end
    end
  end

  private
    def project_params
      params.require(:project).permit(
        :student_id,
        :name,
        :description,
        :capstone,
        :client_work,
        :github,
        :website,
        :screencast,
        :project_image,
        :remove_project_image,
        technology_ids: []
      )
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<section id="content-region-3" class="padding-40 page-tree-bg">
  <div class="container">
    <h3 class="page-tree-text">Edit Project</h3>
  </div>
</section><!--page-tree end here-->

<div class="space-70"></div>
<div class="container project-edit">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="my-login-form">
        <%= form_for(@project, url: project_path(@project)) do |f| %>
          <% if @project.errors.any? %>
            <div class="alert alert-dismissible alert-warning center-warning">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <h3>You forgot to fill out
                <%= pluralize(@project.errors.count, "field") %>:
              </h3>
              <ul>
                <% @project.errors.full_messages.each do |msg| %>
                  <h5><%= msg %></h5>
                <% end %>
              </ul>
            </div>
          <% end %>
          <h4 class="heading-mini">Enter Project Information</h4><hr>
          <div class="form-group">
            <%= f.label :name, "Project Name/Title" %><span class="required-form-field"> *</span><br />
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :description, "Description" %><span class="required-form-field"> *</span><br />
            <%= f.text_area :description, size: "20x5", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.check_box :capstone %>&nbsp;
            <%= f.label :capstone, "This is my capstone project" %>
          </div>
          <div class="form-group">
            <%= f.check_box :client_work %>&nbsp;
            <%= f.label :client_work, "This is client work" %>
          </div><hr>
          <div class="form-group">
            <div class="row">
              <div class="col-md-12 margin-btm-20">
                <%= f.label "Select technologies used in this project" %><span class="required-form-field"> *</span><br /><br />
                <%= f.collection_select( :technology_ids, Technology.all.order(:name), :id, :name, {}, {:prompt => 'Select Fields', class: "form-control chosen-select", multiple: true} )%>
              </div>
            </div>
          </div><hr>
          <div class="form-group">
            <%= f.label :github %><br />
            <%= f.text_field :github, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :website, "Project Website (if deployed)" %><br />
            <%= f.text_field :website, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :screencast, "Screencast/Youtube Video Link (if available)" %><br />
            <%= f.text_field :screencast, class: "form-control" %>
          </div>

          <% if @project.project_image.url && @project.project_image.url.include?("aws") %>
              <div class="form-group">
                <%= f.label :current_image, "Current Image" %><br />
                <%= image_tag @project.project_image.thumb.url, class: "form-img-preview" %>
              </div>
              <div class="form-group">
                <%= f.label :project_image, "Change Image" %><br />
                <%= f.file_field :project_image, class: "form-control" %>
              </div>
          <% else %>
            <div class="form-group">
              <%= f.label :project_image, "Upload Project Screencap/Image (if available)" %><br />
              <%= f.file_field :project_image, class: "form-control" %>
            </div>
          <% end %>
          
          <% if admin_signed_in? %>
            <div class="form-group">
              <%= f.label :student_id, "Student" %><br />
              <%= f.collection_select(:student_id, Student.all, :id, :first_name, :prompt => 'Select Student', class: "form-control") %>
            </div>
          <% elsif student_signed_in? %>
            <div class="form-group">
              <%= f.hidden_field :student_id, class: "form-control", value: @project.student_id %>
            </div>
          <% end %>
          <br>
          <div class="text-right submit-btn">
            <%= f.submit "Update Project", class: "btn theme-btn-color" %>
            <%= link_to "Cancel", project_path(@project), class: "btn theme-btn-color" %>
          </div>
        <% end %><!--login form end-->
      </div>
    </div>
  </div>
</div><!--login page container end-->

<%= render "shared/alerts_checkbox_radio_scripts" %>

app/views/projects/new.html.erb
<section id="content-region-3" class="padding-40 page-tree-bg">
  <div class="container">
    <h3 class="page-tree-text">New Project</h3>
  </div>
</section><!--page-tree end here-->

<div class="space-70"></div>
<div class="container project-new">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="my-login-form">
        <%= form_for(@project, url: projects_path) do |f| %>
          <% if @project.errors.any? %>
            <div class="alert alert-dismissible alert-warning center-warning">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <h3>You forgot to fill out
                <%= pluralize(@project.errors.count, "field") %>:
              </h3>
              <ul>
                <% @project.errors.full_messages.each do |msg| %>
                  <h5><%= msg %></h5>
                <% end %>
              </ul>
            </div>
          <% end %>
          <h4 class="heading-mini">Enter Project Information</h4><hr>
          <div class="form-group">
            <%= f.label :name, "Project Name/Title" %><span class="required-form-field"> *</span><br />
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :description, "Description" %><span class="required-form-field"> *</span><br />
            <%= f.text_area :description, size: "20x5", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.check_box :capstone %>&nbsp;
            <%= f.label :capstone, "This is my capstone project" %>
          </div>
          <div class="form-group">
            <%= f.check_box :client_work %>&nbsp;
            <%= f.label :client_work, "This is client work" %>
          </div><hr>
          <div class="form-group">
            <div class="row">
              <div class="col-md-12 margin-btm-20">
                <%= f.label "Select technologies used in this project" %><span class="required-form-field"> *</span><br /><br />
                <%= f.collection_select( :technology_ids, Technology.all.order(:name), :id, :name, {}, {:prompt => 'Select Fields', class: "form-control chosen-select", multiple: true} )%>
              </div>
            </div>
          </div><hr>
          <div class="form-group">
            <%= f.label :github %><br />
            <%= f.text_field :github, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :website, "Project Website (if deployed)" %><br />
            <%= f.text_field :website, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :screencast, "Screencast/Youtube Video Link (if available)" %><br />
            <%= f.text_field :screencast, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :project_image, "Project Screencap/Image (if available)" %><br />
            <%= f.file_field :project_image, class: "form-control" %>
          </div>
          
          <% if admin_signed_in? %>
            <div class="form-group">
              <%= f.label :student_id, "Student" %><br />
              <%= f.collection_select(:student_id, Student.all, :id, :full_name, :prompt => 'Select Student', class: "form-control") %>
            </div>
          <% elsif student_signed_in? %>
            <div class="form-group">
              <%= f.hidden_field :student_id, class: "form-control", value: current_user.id %>
            </div>
          <% end %>
          <br>
          <div class="text-right submit-btn">
            <%= f.submit "Create Project", class: "btn theme-btn-color" %>
            <% if current_student %>
              <%= link_to "Cancel", student_path(current_student), class: "btn theme-btn-color" %>
            <% elsif current_admin %>
              <%= link_to "Cancel", students_path, class: "btn theme-btn-color" %>
            <% end %>
          </div>
        <% end %><!--login form end-->
      </div>
    </div>
  </div>
</div><!--login page container end-->

<%= render "shared/alerts_checkbox_radio_scripts" %>

app/views/projects/show.html.erb
<div class="project-show">
  <section id="content-region-3" class="padding-40 page-tree-bg">
    <div class="container">
      <h3 class="page-tree-text"><%= @project.name %></h3>
    </div>
  </section><!--page-tree end here-->

  <div class="space-70"></div>
  <div class="container portfolio-details">
    <div class="row">
      <div class="col-md-8 portfolio-single-slide margin-btm-40">
        <div class="flexslider text-center">
          <%= image_tag @project.project_image.large.url %>
        </div><!--flex slider-->
      
        <div class="tabs"><!--tabs start-->
          <ul class="nav nav-tabs">
            <li class="active"><a href="#description" data-toggle="tab"><h4 class="heading-mini tab-name">Description</h4></a></li>
            <% if @project.embed_youtube_screencast %>
              <li class=""><a href="#screencast" data-toggle="tab"><h4 class="heading-mini tab-name">Screencast</h4></a></li>
            <% end %>
          </ul>

          <!-- Tab panes -->
          <div class="tab-content">
            <div class="tab-pane description-pane active" id="description">
              <div class="tab-desc animated fadeInDown">
                <p style="white-space: pre-line;"><%= @project.description %></p>
              </div> 
            </div>
            <% if @project.embed_youtube_screencast %>
              <div class="tab-pane" id="screencast">
                <div class="tab-desc animated fadeIn screencast-iframe embed-responsive embed-responsive-16by9">
                  <iframe src="<%= @project.embed_youtube_screencast %>" frameborder="0" allowfullscreen>Your browser does not support iframe. Click <a href="<%= @project.screencast %>">here</a> to check out the screencast</iframe>
                </div>
              </div>
              <% end %>
            </div>
          </div><!--tabs end-->
      </div>
      <div class="col-md-4">
        <div class="portfolio-side-bar">
          <hr>
          <div class="sidebar-box control-buttons">
            <% if admin_signed_in? || student_signed_in? && current_student.id == @project.student_id %>
              <a href="/projects/<%= @project.id %>/edit" class="btn btn-lg theme-btn-color" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Edit Project"><i class="ion-edit"></i></a> 
              <a href="/projects/<%= @project.id %>" data-method="delete" data-confirm="Are you sure you want to delete '<%= @project.name %>'?" class="btn btn-lg theme-btn-color" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Delete Project"><i class="ion-trash-a"></i></a> 
            <% end %>
            <a href="/students/<%= @project.student_id %>" class="btn btn-lg theme-btn-color" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Back to Student Profile"><i class="ion-person"></i></a> 
          </div>
          <hr>

          <% if @project.project_links? %>
            <div class="sidebar-box">
              <h4 class="project-checkout">Check It Out</h4>
              <ul class=" list-inline social-btn">
                <% unless @project.github == "" || @project.github == nil %> 
                  <li><a href="<%= @project.normalized_github %>" target="_blank"><i class="ion-social-github" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Code On GitHub" target="_blank"></i></a></li>
                <% end %>
                <% unless @project.website == "" || @project.website == nil %> 
                  <li><a href="<%= @project.normalized_website %>" target="_blank"><i class="ion-android-desktop" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Live Website" target="_blank"></i></a></li>
                <% end %>
                <% unless @project.screencast == "" || @project.screencast == nil %> 
                  <li><a href="<%= @project.normalized_screencast %>" target="_blank"><i class="ion-ios-videocam" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Watch App Screencast" target="_blank"></i></a></li>
                <% end %>
              </ul>
            </div>
            <hr>
          <% end %>

          <% if @project.technologies.any? %>
            <div class="sidebar-box">
              <h4>Technologies</h4>
              <ul class="cat-list">  
                <div class="row">
                  <% @technologies.each do |tech| %>
                    <div class="col-sm-6">
                      <li><a href="#" class="hover-color"><%= tech.name %></a></li>
                    </div>
                  <% end %>
                </div>
              </ul>
            </div>
            <hr>
          <% end %>
        </div>
      </div>
    </div>
  </div><!--portfolio single container end-->
</div>