config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => [:registrations], controllers: { 
    sessions: 'admins/sessions',
  }
  authenticate :admin do 
    mount Resque::Server.new, :at => "/dashboard/jobs"
  end  
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'    
    patch 'admins' => 'devise/registrations#update', :as => 'admin_registration'            
  end

  devise_for :students, :skip => [:registrations], controllers: { 
    sessions: 'students/sessions',
  }
  as :student do
    get 'students/edit' => 'devise/registrations#edit', :as => 'edit_student_registration'    
    patch 'students' => 'devise/registrations#update', :as => 'student_registration'            
  end

  devise_for :employers, controllers: { 
    sessions: 'employers/sessions',
    registrations: 'employers/registrations'
  }

  root 'pages#setup_root'
  
  get '/sign_in' => 'pages#sign_in', as: :home_sign_in
  get '/students/invitations/batch' => 'students#batch', as: :student_batch_invite
  get '/employers/invitations/batch' => 'employers#batch', as: :employer_batch_invite
  get '/admins/invitations/batch' => 'admins#batch', as: :admin_batch_invite

  namespace :api do
    namespace :v1 do
      resources :admins
      resources :students
      resources :employers
      resources :employer_email_records
    end
  end

  resources :admins
    get '/dashboard' => 'admins#admin_center', as: :admin_center
    get '/admin/admins/new' => 'admins#new', as: :new_admin_admin
    post '/admin/admins/new' => 'admins#create', as: :admin_admins
    get '/admin/students/new' => 'students#new', as: :new_admin_student
    post '/admin/students' => 'students#create', as: :admin_students
    get '/admin/employers/new' => 'employers#new', as: :new_admin_employer
    post '/admin/employers' => 'employers#create', as: :admin_employers
  
  resources :students
  resources :employers
  resources :projects
  resources :technologies
  resources :salary_ranges
  resources :industries
  resources :position_types
  resources :positions
  resources :cohort_cities
  resources :follow_up_students
  resources :batch_invitations

  post '/employer_emails' => 'employer_emails#create'
  post '/student_emails' => 'student_emails#create'

end

app/models/employer.rb
class Employer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :sign_up_code
  mount_uploader :image, ImageUploader

  # before_update :capitalize_params
  after_create :create_list
  has_one :follow_up_list, dependent: :destroy
  has_and_belongs_to_many :positions
  has_and_belongs_to_many :position_types
  has_and_belongs_to_many :industries
  has_and_belongs_to_many :salary_ranges
  has_and_belongs_to_many :technologies
  has_many :employer_email_records, dependent: :destroy
  has_many :student_email_records, dependent: :destroy

  validates :name, :rep_first_name, :rep_last_name, :rep_email, presence: true
  validates :rep_email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :city, :state, presence: true
  validates :description, presence: true
  validates :number_of_positions, numericality: { only_integer: true, allow_nil: true }
  validates :sign_up_code, on: :create, presence: true, inclusion: { in: [ ENV["sign_up_code_one"], ENV["sign_up_code_two"] ]}, allow_nil: true

  def rep_full_name
    "#{rep_first_name} #{rep_last_name}"
  end

  def normalized_website
    website && PostRank::URI.normalize(website).to_s
  end

  def create_list
    FollowUpList.create(name: "#{self.name}-List", employer_id: self.id)
  end

  def location
    "#{city}, #{state}"
  end

  def hiring_fields?
    fields = false

    if number_of_positions == nil || number_of_positions == ""
      number_of_positions_entered = false
    else
      number_of_positions_entered = true
    end

    if hiring_timeline == nil || hiring_timeline == ""
      hiring_timeline_entered = false
     else
      hiring_timeline_entered = true
    end

    if number_of_positions_entered || hiring_timeline_entered
      fields = true
    end

    fields
  end
end

app/controllers/api/v1/employers_controller.rb
class Api::V1::EmployersController < ApplicationController
  before_action :authenticate_user!

  def index
    @employers = Employer.all
  end
end

app/controllers/employers/confirmations_controller.rb
class Employers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/employers/omniauth_callbacks_controller.rb
class Employers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/employers/passwords_controller.rb
class Employers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/employers/registrations_controller.rb
class Employers::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_sign_up_params, only: [:create]
  before_filter :configure_account_update_params, only: [:update]
  before_filter :authenticate_admin_employer!, except: [:new, :create]
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # # POST /resource
  # def create
  #   super
  # end

  # # GET /resource/edit
  # def edit
  #   super
  # end

  # # PUT /resource
  # def update
  #   super
  # end

  # # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.for(:sign_up) <<
        [ :name,
          :image,
          :remove_image,
          :description,
          :rep_first_name,
          :rep_last_name,
          :rep_phone,
          :rep_email,
          :website,
          :city,
          :state,
          :currently_hiring,
          :hiring_timeline,
          :number_of_positions,
          :company_size,
          :active,
          :hide_profile,
          :allow_emails,
          :sign_up_code,
          :password,
          :password_confirmation,
          :email,
          position_ids: [],
          position_type_ids: [],
          industry_ids: [],
          salary_range_ids: [],
          technology_ids: []
        ]
    end

    # If you have extra params to permit, append them to the sanitizer.
    def configure_account_update_params
      devise_parameter_sanitizer.for(:account_update) << 
        [ :name,
          :image,
          :remove_image,
          :description,
          :rep_first_name,
          :rep_last_name,
          :rep_phone,
          :rep_email,
          :website,
          :city,
          :state,
          :currently_hiring,
          :hiring_timeline,
          :number_of_positions,
          :company_size,
          :active,
          :hide_profile,
          :allow_emails,
          :sign_up_code,
          :password,
          :password_confirmation,
          :current_password,
          :email,
          position_ids: [],
          position_type_ids: [],
          industry_ids: [],
          salary_range_ids: [],
          technology_ids: []
        ]
    end

  # private

  #   def sign_up(resource_name, resource)
  #     true
  #   end


  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employers/sessions_controller.rb
class Employers::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/employers/unlocks_controller.rb
class Employers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!, :only => [:new, :create]
  before_action :authenticate_admin_employer!, :only => [:edit, :update, :destroy]
  
  def index
    @employers = Employer.where(active: true).order(:name)
  end

  def new
    @employer = Employer.new
  end
    
  def create
    @employer = Employer.new(employer_params)

    if @employer.save
      flash[:success] = "Employer account successfully created!"
      redirect_to employer_path(@employer)
    else
      render :new
    end
  end

  def batch
    render 'employers/invitations/batch'
  end

  def show
    @employer = Employer.find(params[:id])
    
    @follow_up_list = @employer.follow_up_list
    @positions = @employer.positions if @employer.positions.any?
    @position_types = @employer.position_types if @employer.position_types.any?
    @industries = @employer.industries.order(:name) if @employer.industries.any?
    @technologies = @employer.technologies.order(:name) if @employer.technologies.any?
    @salary_ranges = @employer.salary_ranges if @employer.salary_ranges.any?
    @follow_up_students = @follow_up_list.follow_up_students if @follow_up_list.follow_up_students.any?
    @student_email = StudentEmail.new
  end

  def edit
    @employer = Employer.find(params[:id])
    
    unless admin_signed_in? || employer_signed_in? && @employer.id == current_employer.id
      redirect_to employers_path
      flash[:warning] = "You do not have access to that page!"
    end
  end

  def update
    @employer = Employer.find(params[:id])

    # Allow employer account update without password
    if admin_signed_in? || employer_signed_in? && @employer.id == current_employer.id
      if employer_params[:password].blank?
        employer_params.delete(:password)
        employer_params.delete(:password_confirmation)
      end

      successfully_updated = if needs_password?(@employer, employer_params)
                               @employer.update(employer_params)
                             else
                               @employer.update_without_password(employer_params)
                             end

      respond_to do |format|
        if successfully_updated
          sign_in(@employer, :bypass => true)
          format.html { redirect_to @employer }
          flash[:success] = "Your account was successfully updated!"
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @employer.errors, status: :unprocessable_entity }
        end
      end
    else 
      redirect_to employers_path
      flash[:warning] = "You do not have access to that page!"
    end
  end

  def destroy
    @employer = Employer.find(params[:id])

    if admin_signed_in? || employer_signed_in? && @employer.id == current_employer.id 
      @employer.remove_image!
      @employer.save

      if @employer.destroy
        flash[:success] = "Employer account successfully deleted!"
        redirect_to root_path
      else
        flash[:warning] = "Unable to delete the employer account."
        Rails.logger.info @employer.errors.messages
      end 
    else
      redirect_to root_path
      flash[:warning] = "You do not have access to that page!"
    end 
  end

  private

    def employer_params
      params.require(:employer).permit(
        :name,
        :image,
        :remove_image,
        :description,
        :rep_first_name,
        :rep_last_name,
        :rep_phone,
        :rep_email,
        :website,
        :city,
        :state,
        :currently_hiring,
        :hiring_timeline,
        :number_of_positions,
        :company_size,
        :active,
        :hide_profile,
        :allow_emails,
        :sign_up_code,
        :password,
        :password_confirmation,
        :email,
        position_ids: [],
        position_type_ids: [],
        industry_ids: [],
        salary_range_ids: [],
        technology_ids: []
      )
    end

    def needs_password?(user, params)
      params[:password].present?
    end
end

app/helpers/api/v1/employers_helper.rb
module Api::V1::EmployersHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/invitations/batch.html.erb
<div class="login-page">
  <section id="content-region-3" class="padding-40 page-tree-bg">
    <div class="container">
      <h3 class="page-tree-text"><%= t "devise.invitations.new.header" %></h3>
    </div>
  </section><!--page-tree end here-->

  <div class="space-70"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="my-login-form">
          <%= form_tag batch_invitations_path, :method => :post do %>
            <h4 class="heading-mini">Enter employer email addresses you'd like to invite</h4>
            <div>Addresses must be separated by a comma to create invitations</div><hr>
            <div class="row">
              <div class="form-group col-md-12">
                <%= text_area_tag :email_addresses, nil, class: "text-emails" %>
                <%= hidden_field_tag 'type', 'employer' %>
              </div>
            </div>
            <div class="row">
              <div class="text-right submit-btn col-md-12">
                <%= submit_tag "Send employer invitation(s)", class: "btn theme-btn-color" %>
              </div>
            </div>
          <% end -%>
        </div>
      </div>
    </div>
  </div><!--login page container end-->
</div>

app/views/employers/invitations/edit.html.erb
<div class="employer-new-admin">
  <section id="content-region-3" class="padding-40 page-tree-bg">
      <div class="container">
          <h3 class="page-tree-text">
              Set Up Employer Account
          </h3>
      </div>
  </section><!--page-tree end here-->

  <div class="space-70"></div>

  <div class="container">
    <%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put } do |f| %>
    <%= f.hidden_field :invitation_token %>
    <%= f.hidden_field :active, value: true %>
    <% if @employer.errors.any? %>
      <div class="alert alert-dismissible alert-warning center-warning">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h3>You forgot to fill out
          <%= pluralize(@employer.errors.count, "field") %>:
        </h3>
        <ul>
          <% @employer.errors.full_messages.each do |msg| %>
            <h5><%= msg %></h5>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="my-login-form col-md-6">
        <div class="login-info-box">
          <h4 class="heading-mini">Log In Information</h4><hr>
          <div class="row">
            <div class="col-md-6 margin-btm-20">
              <%= f.label :name, "Company Name" %><span class="required-form-field"> *</span><br />
              <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="col-md-6 margin-btm-20">
              <%= f.label :email %><span class="required-form-field"> *</span><br />
              <%= f.email_field :email, class: "form-control" %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 margin-btm-20">
              <%= f.label :password %><span class="required-form-field"> *</span><br />
              <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
            </div>
            <div class="col-md-6 margin-btm-20">
              <%= f.label :password_confirmation %><span class="required-form-field"> *</span><br />
              <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
            </div>
          </div>
        </div>
      </div>
      <div class="my-login-form col-md-6">
        <div class="login-info-box">
          <h4 class="heading-mini">Company Representative Details</h4><hr>
          <div class="row">
            <div class="col-md-6 margin-btm-20">
              <%= f.label :rep_first_name %><span class="required-form-field"> *</span><br />
              <%= f.text_field :rep_first_name, class: "form-control" %>
            </div>
             <div class="col-md-6 margin-btm-20">
              <%= f.label :rep_last_name %><span class="required-form-field"> *</span><br />
              <%= f.text_field :rep_last_name, class: "form-control" %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 margin-btm-20">
              <%= f.label :rep_email %><span class="required-form-field"> *</span><br />
              <%= f.email_field :rep_email, class: "form-control" %>
            </div>
            <div class="col-md-6 margin-btm-20">
              <%= f.label :rep_phone %><br />
              <%= f.text_field :rep_phone, class: "form-control" %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="my-login-form col-md-6">
        <div class="login-info-box reg-company-info">
          <h4 class="heading-mini">Company Info</h4><hr>
          <div class="row">
            <div class="col-md-6 margin-btm-20">
              <%= f.label :city %><span class="required-form-field"> *</span><br />
              <%= f.text_field :city, class: "form-control" %>
            </div>
             <div class="col-md-6 margin-btm-20">
              <%= f.label :state %><span class="required-form-field"> *</span><br />
              <%= f.select(:state, options_for_select(us_states, @employer.state), :prompt => "Select State", class: "form-control" ) %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 margin-btm-20">
              <%= f.label :website %><br />
              <%= f.text_field :website, class: "form-control" %>
            </div>
            <div class="col-md-6 margin-btm-20">
              <%= f.label :image, "Company Logo" %><br />
              <%= f.file_field :image, class: "form-control" %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 margin-btm-20">
              <%= f.label "Industry" %><br />
                <%= f.collection_check_boxes :industry_ids, Industry.all, :id, :name do |b| %>
                  <div class="col-md-6 col-sm-6 collection-check-box">
                    <%= b.check_box %>
                    <%= b.label %>
                  </div>
                <% end %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 margin-btm-20">
              <%= f.label :description, "Company Description" %><span class="required-form-field"> *</span><br />
              <%= f.text_area :description, class: "form-control" %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 margin-btm-20">
              <%= f.label "Company Size" %><br />
              <%= f.radio_button :company_size, '1-10' %> &nbsp; 
              <%= f.label :company_size, "1-10" %><br />
              <%= f.radio_button :company_size, "11-50" %> &nbsp;
              <%= f.label :company_size, "11-50" %><br />
              <%= f.radio_button :company_size, "51-200" %> &nbsp;
              <%= f.label :company_size, "51-200" %><br />
              <%= f.radio_button :company_size, "201-500" %> &nbsp;
              <%= f.label :company_size, "201-500" %><br />
              <%= f.radio_button :company_size, "501-1000" %> &nbsp;
              <%= f.label :company_size, "501-1000" %><br />
              <%= f.radio_button :company_size, "1000+" %> &nbsp;
              <%= f.label :company_size, "1000+" %><br />
            </div>
          </div>
        </div>
      </div>
      <div class="my-login-form col-md-6">
        <div class="login-info-box reg-hiring">
          <h4 class="heading-mini">Hiring Needs</h4><hr>
          <div class="row">
            <div class="col-md-12 margin-btm-20">
              <%= f.label :currently_hiring, "Are you currently hiring?" %><br />
              <%= f.radio_button :currently_hiring, "1" %> &nbsp;<%= f.label :currently_hiring, " Yes" %> &nbsp; &nbsp;
              <%= f.radio_button :currently_hiring, "0" %> &nbsp;<%= f.label :currently_hiring, " No" %><br />
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 margin-btm-20">
              <%= f.label :number_of_positions %><br />
              <%= f.text_field :number_of_positions, class: "form-control" %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 col-sm-6 margin-btm-20">
              <%= f.label "Positions Available" %><br />
                <%= f.collection_check_boxes :position_ids, Position.all, :id, :name do |b| %>
                  <div class="collection-check-box">
                    <%= b.check_box %>
                    <%= b.label %>
                  </div>
                <% end %>
            </div>
            <div class="col-md-6 col-sm-6 margin-btm-20">
              <%= f.label "Position Types" %><br />
                <%= f.collection_check_boxes :position_type_ids, PositionType.all, :id, :name do |b| %>
                  <div class="collection-check-box">
                    <%= b.check_box %>
                    <%= b.label %>
                  </div>
                <% end %>
            </div>
          </div> 
          <div class="row">
            <div class="col-md-6 margin-btm-20">
              <%= f.label "Salary Range" %><br />
                <%= f.collection_check_boxes :salary_range_ids, SalaryRange.all.order(:id), :id, :salary_range do |b| %>
                  <div class="collection-check-box">
                    <%= b.check_box %>
                    <%= b.label %>
                  </div>
                <% end %>
            </div>
            <div class="col-md-6 margin-btm-20">
              <%= f.label "How soon will you be hiring?" %><br />
              <%= f.radio_button :hiring_timeline, 'ASAP' %> &nbsp; 
              <%= f.label :hiring_timeline, "ASAP" %><br />
              <%= f.radio_button :hiring_timeline, "0 - 3 Months" %> &nbsp;
              <%= f.label :hiring_timeline, "0 - 3 Months" %><br />
              <%= f.radio_button :hiring_timeline, "3 - 6 Months" %> &nbsp;
              <%= f.label :hiring_timeline, "3 - 6 Months" %><br />
              <%= f.radio_button :hiring_timeline, "Building a Pipeline" %> &nbsp;
              <%= f.label :hiring_timeline, "We're Building A Pipeline" %><br />
              <%= f.radio_button :hiring_timeline, "No Date Yet" %> &nbsp;
              <%= f.label :hiring_timeline, "No Date Yet" %><br />
            </div>
          </div>   
        </div>
      </div>
    </div>
    <div class="row">
      <div class="my-login-form col-md-6">
        <div class="login-info-box reg-company-tech">
          <h4 class="heading-mini">Technologies</h4>
          <hr>
          <div class="row">
            <div class="col-md-12 margin-btm-20">
              <%= f.label "What technologies/languages are you hiring for?" %><br /><br />
              <%= f.collection_select( :technology_ids, Technology.all.order(:name), :id, :name, {}, {:prompt => 'Select Fields', class: "form-control chosen-select", multiple: true} )%>
            </div>
          </div>      
        </div>
      </div>
      <div class="my-login-form col-md-6">
        <div class="login-info-box reg-company-submit">
          <h4 class="heading-mini">Allow Students to Contact Company Rep by Email?</h4><hr>
          <div class="row">
            <div class="col-md-12 margin-btm-20">
              <%= f.radio_button :allow_emails, "1" %> &nbsp;<%= f.label :allow_emails, " Yes" %> &nbsp; &nbsp;
              <%= f.radio_button :allow_emails, "0" %> &nbsp;<%= f.label :allow_emails, " No" %><br />
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 text-right">
              <%= f.submit "Create My Account", class: "btn theme-btn-color" %>
            </div>
            <% end %>    
            <div class="form-btm-link text-center">
             <%= link_to "Already have an account? Log in!", new_employer_session_path %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render "shared/alerts_checkbox_radio_scripts" %>

app/views/employers/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post} do |f| %>
  <%= devise_error_messages! %>

<% resource.class.invite_key_fields.each do |field| -%>
  <p><%= f.label field %><br />
  <%= f.text_field field %></p>
<% end -%>

  <p><%= f.submit t("devise.invitations.new.submit_button") %></p>
<% end %>